name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v3

      - name: Vérifier le contenu du repo
        run: ls -la  # Vérifie les fichiers clonés

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 🔹 Installation & Tests du Backend
      - name: Installer les dépendances du Backend
        run: |
          cd backend
          npm install

      - name: Lint du Backend
        run: |
          cd backend
          npm run lint

      - name: Tests du Backend
        run: |
          cd backend
          npm test

      # 🔹 Installation & Tests du Frontend
      - name: Installer les dépendances du Frontend
        run: |
          cd frontend
          npm install

      - name: Lint du Frontend
        run: |
          cd frontend
          npm run lint

      - name: Tests du Frontend
        run: |
          cd frontend
          npm test
