name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies (Backend)
        run: |
          cd server
          npm ci  # Utilisation de npm ci pour des installations plus rapides et reproductibles

      - name: Run seed (Backend)
        env:
          MONGODB_URI: mongodb://localhost:27017/test
        run: |
          cd server
          npm run seed

      - name: Run tests (Backend)
        env:
          MONGODB_URI: mongodb://localhost:27017/test
        run: |
          cd server
          npm test

  client:
    name: Client Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies (Client)
        run: |
          cd client
          npm ci  # Utilisation de npm ci

      - name: Build Project (Client)
        run: |
          cd client
          npm run build || echo "Build failed, check logs"

      - name: Run tests (Client)
        run: |
          cd client
          npm test || echo "No tests found"