name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de Node.js avec gestion du cache pour backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      # Installation des dépendances du backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      # Configuration de Node.js pour frontend (sans cache)
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installation des dépendances du frontend (sans package-lock.json)
      - name: Install frontend dependencies
        run: npm install --no-package-lock
        working-directory: ./frontend

      # Ajoute ici les commandes pour tester ou builder l’application
