name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v3

      - name: Vérifier la structure du projet
        run: ls -R  # Affiche l'arborescence des fichiers pour voir où sont package.json

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 🔹 Backend
      - name: Installer les dépendances du Backend
        run: |
          cd backend
          npm install

      - name: Lancer les tests du Backend
        run: |
          cd backend
          npm test

      # 🔹 Frontend Back-Office
      - name: Installer les dépendances du Frontend Back-Office
        run: |
          cd frontend/back-office
          npm install

      - name: Lancer les tests du Frontend Back-Office
        run: |
          cd frontend/back-office
          npm test

      # 🔹 Frontend Front-Office
      - name: Installer les dépendances du Frontend Front-Office
        run: |
          cd frontend/front-office
          npm install

      - name: Lancer les tests du Frontend Front-Office
        run: |
          cd frontend/front-office
          npm test
